apiVersion: v1
kind: Pod
metadata:
  name: iperf3-vm3
spec:
  containers:
  - name: iperf3-vm3
    image: tjcw/iperf3
    ports:
    - containerPort: 5000
  nodeSelector:
    kubernetes.io/hostname: kind-worker
