#!/bin/bash -x
function run_server()
{
  kubectl run pod1 --image=networkstatic/iperf3 --overrides='{"spec": { "nodeSelector": {"kubernetes.io/hostname": "tjcw-kube-1"}}}' --command -- iperf3 -s 
}

function run_client()
{
  ipq=$(kubectl get pods pod1 -o json|jq ".status.podIP")
  ipq1=${ipq#\"}
  ip=${ipq1%\"}
  kubectl run pod2 --image=networkstatic/iperf3 --overrides='{"spec": { "nodeSelector": {"kubernetes.io/hostname": "tjcw-kube-2"}}}' --command -- iperf3 -c $ip -t 70
}

function hostip_of()
{
  hostipq=$(kubectl get pods $1 -o json|jq ".status.hostIP")
  hostipq1=${hostipq#\"}
  hostip=${hostipq1%\"}
  echo $hostip
}

function uid_of()
{
  uidq=$(kubectl get pods $1 -o json|jq ".metadata.uid")
  uidq1=${uidq#\"}
  uid=${uidq1%\"}
  echo $uid
}
#sudo sh -c "echo 0  > /proc/sys/kernel/kptr_restrict"
#sudo sh -c "echo -1 > /proc/sys/kernel/perf_event_paranoid"
run_server
server_hostip=$(hostip_of pod1)
server_uid=$(uid_of pod1)
sleep 10
run_client
client_hostip=$(hostip_of pod2)
client_uid=$(uid_of pod2)
sleep 5
server_start_cpu=$(ssh -n ${server_hostip} cat /sys/fs/cgroup/cpuacct/kubepods/besteffort/pod${server_uid}/cpuacct.usage)
client_start_cpu=$(ssh -n ${client_hostip} cat /sys/fs/cgroup/cpuacct/kubepods/besteffort/pod${client_uid}/cpuacct.usage)
ssh -n ${server_hostip} perf record -g -a -o perf.data -e cycles -G kubepods/besteffort/pod${server_uid} sleep 60 &
ssh -n ${client_hostip} perf record -g -a -o perf.data -e cycles -G kubepods/besteffort/pod${client_uid} sleep 60
wait
server_end_cpu=$(ssh -n ${server_hostip} cat /sys/fs/cgroup/cpuacct/kubepods/besteffort/pod${server_uid}/cpuacct.usage)
client_end_cpu=$(ssh -n ${client_hostip} cat /sys/fs/cgroup/cpuacct/kubepods/besteffort/pod${client_uid}/cpuacct.usage)
sleep 20
kubectl logs pod1 --tail=10
ssh -n ${server_hostip} perf script|~/workspace/ebpf-performance/container/stackcollapse-perf.pl|~/workspace/ebpf-performance/container/flamegraph.pl >server-flamegraph.svg
ssh -n ${client_hostip} perf script|~/workspace/ebpf-performance/container/stackcollapse-perf.pl|~/workspace/ebpf-performance/container/flamegraph.pl >client-flamegraph.svg
typeset -i server_cpu=${server_end_cpu}-${server_start_cpu}
typeset -i client_cpu=${client_end_cpu}-${client_start_cpu}
echo "server cpu=${server_cpu}"
echo "client cpu=${client_cpu}"
#kubectl delete pod pod1
#kubectl delete pod pod2
